name: Hello world

on: [push]

jobs:
  hello-world:
    runs-on: ubuntu-22.04
    # Map a step output to a job output
    outputs:
      image_tag: ${{ steps.set_image_tag.outputs.image_tag }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Install Dependencies
        run: npm ci

      - name: Test
        run: npx jest

      - name: Set latest tag
        id: set_image_tag
        run: |
          echo "image_tag=v1.0.2" >> $GITHUB_OUTPUT

  release:
    runs-on: ubuntu-20.04
    needs: hello-world

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Install Dependencies
        run: npm ci

      - name: Release new version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run semantic-release

      - name: Tag docker image
        run: |
          latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo "Latest tag: $latest_tag"