name: Hello world

on: [push]

jobs:
  hello-world:
    runs-on: ubuntu-22.04
    # Map a step output to a job output
    outputs:
      image_tag: ${{ steps.set_image_tag.outputs.image_tag }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Hello world
        run: |
          echo "Hello world"

      - name: Set latest tag
        id: set_image_tag
        run: |
          echo "this commit hash >> ${{ github.sha }}"
          echo "image_tag=v1.0.2" >> $GITHUB_STATE
          echo "image_tag=v1.0.2" >> $GITHUB_OUTPUT

  deploy:
    runs-on: ubuntu-20.04
    needs: hello-world

    steps:
      - name: echo
        run: |
          echo "output ${{ needs.hello-world.outputs }}"
          echo "Image tag is ${{ needs.hello-world.outputs.image_tag }}"
